name: MLflow CI Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas numpy
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager=local
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifact
          path: mlruns
