name: MLflow Project CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retraining:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting MLflow Project CI"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project
        run: |
          mlflow run . --env-manager=local --experiment-name SMSML_Najwan_Mursyidan

      - name: Get latest MLflow run_id
        working-directory: MLProject
        run: |
          python - <<'PY'
          import os
          from pathlib import Path
          runs = list(Path('mlruns').rglob('meta.yaml'))
          print(f'Jumlah file meta MLflow: {len(runs)}')
          PY

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: MLProject/mlruns
